import { useAuth } from "@clerk/expo";
import axios from "axios";
import { useEffect } from "react";

// Using localhost for api url won't work when access the data via physical mobile (because localhost would mean the mobile itself)
// To make it works, we have to use Ngrok so that we can access the api in local development (localhost) from physical mobile,
// via public url that was generated by Ngrok.
const API_URL = process.env.EXPO_PUBLIC_API_URL;

const api = axios.create({
  baseURL: API_URL,
  headers: {
    "Content-Type": "application/json"
  },
});

export const useApi = () => {
  const { getToken } = useAuth();
  
  useEffect(() => {
    const interceptor = api.interceptors.request.use(async (config) => {
      const token = await getToken();

      if (token) {
        config.headers.Authorization = `Bearer ${token}`;
      }

      return config;
    });

    // cleanup
    return () => {
      api.interceptors.request.eject(interceptor);
    };
  }, [getToken]);

  return api;
};